# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e8bEqgbiGBE-AeFbFIiC-VpO3OUM-EEJ
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
import rasterio

# --- Konfiguracja wejściowa ---
time_points = ['1985', '1993', '2001', '2011']
image_files = [f'{y}.png' for y in time_points]

# Progi klasyfikacji roślinności dla każdego indeksu
classification_thresholds = {
    'VARI':    0.05,
    'GLI':     0.08,
    'VIGREEN': 0.05,
}

# Przechowywanie wyników procentowego pokrycia roślinnością
coverage_results = {key: [] for key in classification_thresholds}

DIV_GUARD = 1e-8  # zabezpieczenie przed dzieleniem przez zero

# --- Analiza RGB dla każdego roku ---
for year, fname in zip(time_points, image_files):
    raw = cv2.imread(fname)
    if raw is None:
        print(f"[POMINIĘTO] Brak pliku: {fname}")
        continue

    # Konwersja BGR → RGB
    scene = cv2.cvtColor(raw, cv2.COLOR_BGR2RGB)

    # Wyrównanie histogramu przez kanał V w HSV (tylko wizualizacja)
    hsv = cv2.cvtColor(scene, cv2.COLOR_RGB2HSV)
    h_ch, s_ch, v_ch = cv2.split(hsv)
    hsv_eq = cv2.merge((h_ch, s_ch, cv2.equalizeHist(v_ch)))
    scene_eq = cv2.cvtColor(hsv_eq, cv2.COLOR_HSV2RGB)

    # Kanały jako float32 (oryginał, bez wyrównania)
    ch_r = scene[:, :, 0].astype(np.float32)
    ch_g = scene[:, :, 1].astype(np.float32)
    ch_b = scene[:, :, 2].astype(np.float32)

    # Obliczenie indeksów wegetacyjnych
    idx_vari    = (ch_g - ch_r) / (ch_g + ch_r - ch_b + DIV_GUARD)
    idx_gli     = (2 * ch_g - ch_r - ch_b) / (2 * ch_g + ch_r + ch_b + DIV_GUARD)
    idx_vigreen = (ch_g - ch_r) / (ch_g + ch_r + DIV_GUARD)

    # Maski binarne po progowaniu
    mask_vari    = idx_vari    > classification_thresholds['VARI']
    mask_gli     = idx_gli     > classification_thresholds['GLI']
    mask_vigreen = idx_vigreen > classification_thresholds['VIGREEN']

    # Procentowy udział pikseli sklasyfikowanych jako roślinność
    n_pixels = ch_r.size
    coverage_results['VARI'].append(mask_vari.sum()    / n_pixels * 100)
    coverage_results['GLI'].append(mask_gli.sum()      / n_pixels * 100)
    coverage_results['VIGREEN'].append(mask_vigreen.sum() / n_pixels * 100)

    # Wizualizacja wyników dla danego roku
    fig, axes = plt.subplots(1, 5, figsize=(20, 4))
    fig.suptitle(f'Analiza dla roku {year}')

    axes[0].imshow(scene_eq);        axes[0].set_title("RGB Eq");        axes[0].axis('off')
    axes[1].imshow(idx_vari,    cmap='RdYlGn', vmin=-1, vmax=1)
    axes[1].set_title("VARI");       axes[1].axis('off')
    axes[2].imshow(mask_vari,   cmap='viridis')
    axes[2].set_title("VARI Thresh"); axes[2].axis('off')
    axes[3].imshow(mask_gli,    cmap='viridis')
    axes[3].set_title("GLI Thresh");  axes[3].axis('off')
    axes[4].imshow(mask_vigreen, cmap='viridis')
    axes[4].set_title("VIGREEN Thresh"); axes[4].axis('off')

    plt.show()

# --- Wykres zmian zalesienia w czasie (RGB) ---
plt.figure(figsize=(10, 6))
for index_name, values in coverage_results.items():
    plt.plot(time_points, values, marker='o', label=index_name)

plt.title('Procent powierzchni zalesienia w czasie')
plt.xlabel('Rok')
plt.ylabel('Procent powierzchni zalesienia (%)')
plt.ylim(0, 100)
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

print("Zastosowane progi:")
print(classification_thresholds)


# ============================================================
# Wielospektralna analiza NDVI (pliki .tif)
# ============================================================

multispectral_files = ['1985api.tif', '1993api.tif', '2001api.tif', '2011api.tif']
ndvi_coverage = []
NDVI_THRESHOLD = 0.2

for tif_path in multispectral_files:
    try:
        with rasterio.open(tif_path) as dataset:
            band_red = dataset.read(3).astype('float32')
            band_nir = dataset.read(4).astype('float32')

            ndvi_map  = (band_nir - band_red) / (band_nir + band_red + DIV_GUARD)
            ndvi_mask = ndvi_map > NDVI_THRESHOLD

            forest_pct = ndvi_mask.sum() / ndvi_mask.size * 100
            ndvi_coverage.append(forest_pct)

            plt.imshow(ndvi_map, cmap='RdYlGn', vmin=-1, vmax=1)
            plt.title(f'NDVI {tif_path}')
            plt.colorbar()
            plt.show()

            plt.imshow(ndvi_mask, cmap='viridis')
            plt.title(f'NDVI Mask {tif_path}')
            plt.show()

    except Exception as err:
        print(f"Błąd przetwarzania {tif_path}: {err}")

# --- Wykres słupkowy NDVI ---
plt.figure(figsize=(10, 6))
plt.bar(time_points, ndvi_coverage, color='tab:blue')
plt.title('Analiza wylesienia (NDVI)')
plt.xlabel('Lata')
plt.ylabel('Procent powierzchni zalesienia (%)')
plt.ylim(0, 100)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()